import numpy as np
import Tools as tl
import Read as rd
import globalvalue as gb
##############################
DT=10 #一个时间步的长度
DTDN=36400 #时间步数
IC=55 #列
AHO=1 #水平黏性扩散系数
AHD=1 #控制水平扩散
AVO=0.001 #垂直黏性扩散系数
JC=15 #行
KC=3  #层数
LC=563 #一头一尾
LVC=561 #真实网格
DZC=np.array([0.333,0.3333,0.3333])
NQSIJ=11
NPSIJ=11
Cell=np.zeros((IC,JC))
IL=np.arange(LC)
JL=np.arange(LC)
LCT=np.arange(LC)
LNC=np.arange(LC)
LSC=np.arange(LC)
LIJ=np.zeros((IC+1,JC+1),dtype=np.int32)
UV=np.arange(LC)
U1V=np.arange(LC)
VU=np.arange(LC)
V1U=np.arange(LC)
AH=np.zeros((LC,KC))

gb._init()
gb.set_value('NQSIJ',NQSIJ)
gb.set_value('NPSIJ',NPSIJ)
gb.set_value('AH',AH)
gb.set_value('AHD',AHD)
gb.set_value('Cell',Cell)
gb.set_value('IC',IC)
gb.set_value('JC',JC)
gb.set_value('LC',LC)
gb.set_value('LVC',LVC)
gb.set_value('IL',IL)
gb.set_value('JL',JL)
gb.set_value('LCT',LCT)
gb.set_value('LNC',LNC)
gb.set_value('LSC',LSC)
gb.set_value('LIJ',LIJ)
gb.set_value('UV',UV)
gb.set_value('VU',VU)
gb.set_value('U1V',U1V)
gb.set_value('V1U',V1U)
gb.set_value('DT',DT)
gb.set_value('DZC',DZC)
gb.set_value('AHO',AHO)
################################
###开始
########################
###读取文件部分
rd.Read_cell(IC,JC)
rd.Read_dxdy(IC,JC)
rd.Read_lxly(IC,JC)
tl.Cal_LCT_IL_JL(IC,JC,LC)
tl.Cal_Dx_Dy_HM(IC,JC,LC)
rd.Read_Qinp(NQSIJ)
rd.Read_Pinp(NPSIJ)
tl.Cal_Sub_Svb(IC,JC,LC)
tl.Cal_reset_Dx_Dy_Rss(IC,JC,LC)
#处理QSER,MQSER
################################################
#初始化 一部分变量
W=np.zeros((LC,KC))
W1=np.zeros((LC,KC))
U=np.zeros((LC,KC))
V=np.zeros((LC,KC))
UHDYE=np.arange(LC)
UHDYE[:]=0
VHDXE=np.arange(LC)
VHDXE[:]=0
UHDY=np.zeros((LC,KC))
UHDY[:]=0
VHDX=np.zeros((LC,KC))
VHDX[:]=0
U2=np.zeros((LC,KC))
V2=np.zeros((LC,KC))
W2=np.zeros((LC,KC))
UHE=np.arange(LC)
VHE=np.arange(LC)
FUHU=np.zeros((LC,KC))
FUHV=np.zeros((LC,KC))
FVHU=np.zeros((LC,KC))
FVHV=np.zeros((LC,KC))
FWU=np.zeros((LC,KC))
FWV=np.zeros((LC,KC))
gb.set_value('U2',U2)
gb.set_value('V2',V2)
gb.set_value('W2',W2)
gb.set_value('UHE',UHE)
gb.set_value('VHE',VHE)
gb.set_value('FWU',FWU)
gb.set_value('FWV',FWV)
gb.set_value('FUHU',FUHU)
gb.set_value('FUHV',FUHV)
gb.set_value('FVHU',FVHU)
gb.set_value('FVHV',FVHV)
gb.set_value('W',W)
gb.set_value('W1',W1)
gb.set_value('U',U)
gb.set_value('V',V)
gb.set_value('UHDYE',UHDYE)
gb.set_value('VHDXE',VHDXE)
gb.set_value('UHDY',UHDY)
gb.set_value('VHDX',VHDX)
#######################################
#弗劳德数
CFLUUU=np.zeros((LC,KC))
CFLVVV=np.zeros((LC,KC))
CFLWWW=np.zeros((LC,KC))
CFLCAC=np.zeros((LC,KC))
######################################
ICORDYU=np.arange(LC)
ICORDXV=np.arange(LC)
gb.set_value('ICORDYU',ICORDYU)
gb.set_value('ICORDXV',ICORDXV)
####################################
Dxu1=np.zeros((LC,KC))#Cal_HDMF
Dyv1=np.zeros((LC,KC))
Dyu1=np.zeros((LC,KC))
Dxv1=np.zeros((LC,KC))
Sxy=np.zeros((LC,KC))
gb.set_value('Dxu1',Dxu1)
gb.set_value('Dyv1',Dyv1)
gb.set_value('Dyu1',Dyu1)
gb.set_value('Dxv1',Dxv1)
gb.set_value('Sxy',Sxy)
FMDUX=np.zeros((LC,KC))
FMDUY=np.zeros((LC,KC))
FMDVX=np.zeros((LC,KC))
FMDVY=np.zeros((LC,KC))
FCAXE=np.arange(LC)#科氏力
FCAYE=np.arange(LC)#科氏力
FXE=np.arange(LC)
FX=np.zeros((LC,KC))
FY=np.zeros((LC,KC))
FYE=np.arange(LC)
gb.set_value('FX',FX)
gb.set_value('FY',FY)
gb.set_value('FCAXE',FCAXE)
gb.set_value('FCAYE',FCAYE)
gb.set_value('FXE',FXE)
gb.set_value('FYE',FYE)
gb.set_value('FMDUX',FMDUX)
gb.set_value('FMDUY',FMDUY)
gb.set_value('FMDVX',FMDVX)
gb.set_value('FMDVY',FMDVY)
Dxu1=np.zeros((LC,KC))
Dyv1=np.zeros((LC,KC))
Dyu1=np.zeros((LC,KC))
Dxv1=np.zeros((LC,KC))
Sxy=np.zeros((LC,KC))
gb.set_value('Dxu1',Dxu1)
gb.set_value('Dyv1',Dyv1)
gb.set_value('Dyu1',Dyu1)
gb.set_value('Dxv1',Dxv1)
gb.set_value('Sxy',Sxy)
TBX=np.arange(LC)
TBX[:]=0
TBY=np.arange(LC)
TBY[:]=0
TSY=np.arange(LC)
TSY[:]=0
TSX=np.arange(LC)
TSX[:]=0
gb.set_value('TBX',TBX)
gb.set_value('TBY',TBY)
gb.set_value('TSX',TSX)
gb.set_value('TSY',TSY)
###############################################
##########水深流动偏差
DT2=DT/2
gb.set_value('DT2',DT2)
######################
########计算Av
#######################
FUHDYE=np.arange(LC)
FVHDXE=np.arange(LC)
gb.set_value('FUHDYE',FUHDYE)
gb.set_value('FVHDXE',FVHDXE)
#####################################
####HDMT2
tl.Reset_1V()
tl.Cal_UV_VU(IC,JC,KC,LC)
tl.Cal_init_STBXY(IC,JC,KC,LC)
tl.Cal_STBXY(IC,JC,LC)
tl.Cal_HDMF(IC,JC,LC,KC)

